spring.application.name=privacy-shield

spring.datasource.url=jdbc:postgresql://localhost:5432/privacy_shield
spring.datasource.username=postgres
spring.datasource.password=amrit
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG